name: Detect Changes

on:
    workflow_call:
        outputs:
            node:
                description: 'Whether there are changes in the node directory'
                value: ${{ jobs.filter.outputs.node }}
            dotnet:
                description: 'Whether there are changes in the dotnet directory'
                value: ${{ jobs.filter.outputs.dotnet }}

permissions:
    contents: read
    pull-requests: read

jobs:
    filter:
        runs-on: ubuntu-latest

        outputs:
            node: ${{ steps.filter.outputs.node }}
            dotnet: ${{ steps.filter.outputs.dotnet }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Check for changes
              uses: dorny/paths-filter@v4
              id: filter
              with:
                filters: |
                    node:
                        - 'apps/web/main/**'
                        - 'apps/web/ecommerce/**'
                        - 'packages/**'
                        - 'libs/**'
                        - 'next.config.js'
                        - 'tsconfig.json'
                        - 'package.json'
                        - 'package-lock.json'
                    dotnet:
                        - 'apps/api/core/api-crm/**'
                        - 'apps/api/core/api-hrm/**'
                        - 'apps/api/core/api-scm/**'
                        - 'apps/api/core/api-pos/**'
                        - 'apps/api/shared/api-auth/**'
                        - 'apps/api/shared/api-file/**'
                        - 'apps/api/shared/api-logs/**'
                        - 'apps/api/shared/api-notification/**'
                        - 'docker-compose.yml'
                        - '.env.example'

                    